server:
#  port: 8087
  servlet:
    contextPath: /stock
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  forward-headers-strategy: framework
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  resources:
    static-locations: file:/opt/stock/static/
  data:
    mongodb:
      uri: mongodb+srv://${db-username}:${mongo-db-password}@cluster0.ch4qx5m.mongodb.net/?retryWrites=true&w=majority&appName=gurula

  cache:
    type: redis
  redis:
    host: localhost           # Redis 主機 IP 或網域
    port: 6379                 # Redis 預設端口
    password: ${db-password}   # 若有設定 Redis 密碼才需要這行
    ssl: false                 # 通常本地或內部網路不用 SSL

  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: https://gurula.cc/stock/login/oauth2/code/google
            client-id: ${google-client-id}
            client-secret: ${google-client-secret}
            scope:
              - email
              - profile
          line:
            client-id: ${line-client-id}
            client-secret: ${line-client-secret}
            redirect-uri: https://gurula.cc/stock/callback
            scope:
              - openid
              - profile
            authorization-grant-type: authorization_code
        provider:
          line:
            authorization-uri: https://access.line.me/oauth2/v2.1/authorize
            token-uri: https://api.line.me/oauth2/v2.1/token
            user-info-uri: https://api.line.me/v2/profile
            user-name-attribute: userId

springdoc:
  swagger-ui:
    url: /v3/api-docs
  server:
    url: https://gurula.cc

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: INFO

config:
  globalDomain: https://gurula.cc/stock/
  picSavePath: /opt/stock/image/
  picShowPath: https://gurula.cc/stock/uploads/
  jsonPath: /opt/stock/static/data/
  ohlcDataStorePath: /opt/data/stock
