server:
  port: 8087
  servlet:
    contextPath: /stock
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  resources:
    static-locations: classpath:/static/
  data:
    mongodb:
#      uri: mongodb://localhost:27017
      uri: mongodb+srv://${db-username}:${mongo-db-password}@gurula.y2btcof.mongodb.net/?retryWrites=true&w=majority&appName=gurula

  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: http://localhost:8086/talkyo/login/oauth2/code/google
            client-id: ${google-client-id}
            client-secret: ${google-client-secret}
            scope:
              - email
              - profile
          line:
            client-id: ${line-client-id}
            client-secret: ${line-client-secret}
            redirect-uri: http://localhost:8086/talkyo/callback
            scope:
              - openid
              - profile
            authorization-grant-type: authorization_code
        provider:
          line:
            authorization-uri: https://access.line.me/oauth2/v2.1/authorize
            token-uri: https://api.line.me/oauth2/v2.1/token
            user-info-uri: https://api.line.me/v2/profile
            user-name-attribute: userId

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: INFO

config:
  globalDomain: http://localhost:8087/stock/
  picSavePath: /Users/chenyifan/Documents/workspace-fan/stockMate/image/
  picShowPath: http://localhost:8087/stock/image/
  jsonPath: /Users/chenyifan/Documents/workspace-fan/stockMate/src/main/resources/static/data/