server:
  port: 8087
  servlet:
    contextPath: /stock
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  resources:
    static-locations: file:/Users/chenyifan/Documents/workspace-fan/stockMate/src/main/resources/static/
  data:
    mongodb:
      uri: mongodb://localhost:27017

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: INFO

config:
  globalDomain: http://localhost:8087/stock/
  picSavePath: /Users/chenyifan/Documents/workspace-fan/stockMate/image/
  picShowPath: http://localhost:8086/stock/image/
  jsonPath: /Users/chenyifan/Documents/workspace-fan/stockMate/src/main/resources/static/data/